language: elixir

sudo: false

elixir:
  - 1.4

otp_release:
  - 18.2
  - 19.3

env: MIX_ENV=test

script:
  - mix compile
  - ls _build/test/lib/petrovich_elixir/ebin
  - mix coveralls.travis
  - mix credo --strict

notifications:
  email: false
